---
# tasks file for roles/python_role

- name: python3 
  apt: 
    name: python3
    state: latest
    update_cache: YES

- name: pip3
  apt:
    name: python3-pip
    state: latest
    update_cache: YES

- name: pip3 as default 
  command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

- name: python3 as default
  command: update-alternatives --install /usr/bin/python python /usr/bin/python3 10 
