---
# tasks file for roles/c_nagiosmain

- name: extracting nagios 
  unarchive: 
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    remote_src: yes 

- name: nagios configuration
  command: ./configure --with-command-group=nagiosxi 
  args: 
    chdir: /tmp/nagios-4.4.5 

- name: make clean
  make: 
    target: clean
    chdir: /tmp/nagios-4.4.5 

- name: make all
  make: 
    target: all
    chdir: /tmp/nagios-4.4.5

- name: make install 
  make: 
    target: install
    chdir: /tmp/nagios-4.4.5 

- name: make install init
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5 

- name: make install daemon init 
  make:
    target: install-daemoninit 
    chdir: /tmp/nagios-4.4.5 

- name: make install config
  make: 
    target: install-config 
    chdir: /tmp/nagios-4.4.5 

- name: make install commandmode 
  make: 
    target: install-commandmode 
    chdir: /tmp/nagios-4.4.5 

- name: make install exfoliation
  make:
    target: install-exfoliation
    chdir: /tmp/nagios-4.4.5 

- name: webconf
  make:
    target: install-webconf
    chdir: /tmp/nagios-4.4.5 

- name: install passlib 
  pip:
    name: passlib 

- name: user authentication 
  htpasswd: 
    path: /usr/local/nagios/etc/htpasswd.users
    name: user 
    password: password 

- name: restart httpd 
  service: 
    name: httpd
    state: restarted 
    enabled: yes 

     




























